# --- INPUT & MONITOR ---
monitor=,3440x1440@144,auto,1.0
xwayland {
    force_zero_scaling = true
}

misc {
    vrr = 2
}

input {
    kb_layout = fr
    follow_mouse = 1
accel_profile = flat
sensitivity = 0
}

# --- LOOK & LAYOUT ---
general {
    gaps_in = 5
    gaps_out = 60 300 60 300
    border_size = 0
    layout = master
}

decoration {
    dim_special = 0.1
    rounding = 15
    blur {
    enabled = true
    size = 8
    passes = 2
    special = true
    new_optimizations = true
}
}

master {
    mfact = 0.70
}

workspace = 1, gapsout:60 500 60 500
workspace = 2, layoutopt:mfact:0.7

# --- RÈGLES WINDOW ---
windowrule = match:class Cider, workspace special:cider silent, float on
bind = SUPER, M, togglespecialworkspace, cider

windowrule = match:class org.gnome.Nautilus, workspace special:files silent, float on
bind = SUPER, E, togglespecialworkspace, files

windowrule = match:class steam, workspace 2 silent
windowrule = match:class discord, workspace 2 silent

windowrule = match:class org.gnome.Nautilus, size 1200 800
windowrule = match:class cider, size 1200 800

$mainMod = SUPER
bind = $mainMod, C, killactive
bind = $mainMod, Q, exec, kitty
bind = $mainMod, R, exec, rofi -show drun
bind = $mainMod SHIFT, M, exit
bind = SUPER, F, fullscreen, 0
bindm = $mainMod, mouse:273, resizewindow
bindm = $mainMod, mouse:272, movewindow

# --- ENVIRONNEMENT ---
env = QT_QPA_PLATFORMTHEME,qt6ct
env = QT_STYLE_OVERRIDE,kvantum
env = GDK_SCALE,1
env = QT_SCALE_FACTOR,1
env = QT_AUTO_SCREEN_SCALE_FACTOR,0
env = XCURSOR_SIZE,24
env = XDG_SESSION_TYPE,wayland
env = XDG_CURRENT_DESKTOP,Hyprland
env = WAYLAND_DISPLAY,wayland-1

# Aller au workspace N
bind = $mainMod, ampersand, workspace, 1
bind = $mainMod, eacute, workspace, 2
bind = $mainMod, quotedbl, workspace, 3

# Déplacer une fenêtre vers workspace N
bind = $mainMod SHIFT, ampersand, movetoworkspace, 1
bind = $mainMod SHIFT, eacute, movetoworkspace, 2
bind = $mainMod SHIFT, quotedbl, movetoworkspace, 3

# --- LANCEMENT ---
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = sleep 2 && while true; do waybar; sleep 1; done
exec-once = [workspace 2 silent] steam  -windowed
exec-once = [workspace 2 silent] sleep 20 && flatpak run com.discordapp.Discord
exec-once = Cider --minimize
exec-once = files --minimizedd
exec-once = while true; do dunst; sleep 1; done
exec-once = hypridle
exec-once = awww-daemon
exec-once = awww img /home/guillaume/Images/WonderWall-6ldpox.jpg
exec-once = ddcutil getvcp 10 --brief 2>/dev/null | awk '/^VCP/{print $4}' > /tmp/brightness_cache
exec-once = /usr/lib/polkit-kde-authentication-agent-1

# --- ANIMATIONS ---
animations {
    enabled = true
    bezier = myBezier, 0.1, 0.9, 0.1, 1.1
    animation = windows, 1, 7, myBezier
    animation = windowsOut, 1, 7, default, popin 80%
    animation = border, 1, 10, default
    animation = fade, 2, 7, default
    animation = workspaces, 1, 6, default
}

layerrule = ignore_alpha 0.5, match:namespace swaync-control-center
layerrule = ignore_alpha 0.5, match:namespace swaync-notification-window
layerrule = blur on, match:namespace swaync-control-center
layerrule = ignore_alpha 0.3, match:namespace swaync-control-center
layerrule = blur on, match:namespace swaync-notification-window
layerrule = ignore_alpha 0.3, match:namespace swaync-notification-window
layerrule = blur on, match:namespace rofi
layerrule = ignore_alpha 0.3, match:namespace rofi
layerrule = blur on, match:namespace rofi
layerrule = ignore_alpha 0.9, match:namespace rofi
