general {
    lock_cmd = pidof hyprlock || hyprlock
    before_sleep_cmd = loginctl lock-session
after_sleep_cmd = sleep 1 && hyprctl dispatch dpms on
}

# 1. BAISSE LUMINOSITÉ (2 min)
listener {
    timeout = 120
    on-timeout = ddcutil setvcp 10 10
    on-resume = ddcutil setvcp 10 $(cat /tmp/brightness_cache)
}


# 2. VERROUILLAGE (5 min)
listener {
    timeout = 300
    on-timeout = loginctl lock-session
}
# 3. ÉCRAN ÉTEINT (6 min)
listener {
    timeout = 360
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}

# 4. SUSPEND (15 min)
listener {
    timeout = 900
    on-timeout = ~/.config/hypr/lockscreen.sh && systemctl suspend --ignore-inhibitors
    ignore_inhibit = true
}
